### ISSUE TITLE
기존 Atoms/Chip을 Core/Chip으로 재생성 및 구현

### ISSUE THREAD

**Issue by unsnruu** [numble-jjan/jjan-front-renewal#50]
# Description
기존에 Atoms/Chip에 위치한 컴포넌트를 
Core/Chip으로 재생성하여 구현하도록 합니다.
(다만 Atoms/Chip의 경우 Core로 변경하는 작업이 끝난 뒤 삭제하도록 하겠습니다.)

# Todo
- [x] Core/Chip에 `index.tsx`, `index.style.ts` 파일을 생성합니다.
- [x] Atoms/Chip의 구현된 로직을 붙여 넣습니다.
- [x] 필요할 경우 작성 스타일에 맞추어 코드를 리팩토링 하겠습니다.
- [ ] #53
- [x] 삭제 기능을 추가적으로 구현합니다.
- [x] `index.stories.tsx` 파일을 작성 후 스토리북에 UI를 렌더링 하겠습니다.
